// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package DataBase

import (
	"database/sql"
)

type Equipo struct {
	ID     int32
	Nombre string
}

type Liga struct {
	ID     int32
	Nombre string
	Pais   string
}

type Partido struct {
	ID                int32
	LigaID            int32
	EquipoLocalID     int32
	EquipoVisitanteID int32
	GolesLocal        sql.NullInt32
	GolesVisitante    sql.NullInt32
	Estado            sql.NullString
}

type TablaPosicione struct {
	ID                int32
	LigaID            int32
	EquipoID          int32
	Puntos            sql.NullInt32
	PartidosJugados   sql.NullInt32
	PartidosGanados   sql.NullInt32
	PartidosEmpatados sql.NullInt32
	PartidosPerdidos  sql.NullInt32
}
