// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package DataBase

import (
	"context"
	"database/sql"
)

const createEquipo = `-- name: CreateEquipo :one

INSERT INTO equipos (nombre) 
VALUES ($1) 
RETURNING id, nombre
`

// CRUD PARA LA TABLA: EQUIPOS
func (q *Queries) CreateEquipo(ctx context.Context, nombre string) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, createEquipo, nombre)
	var i Equipo
	err := row.Scan(&i.ID, &i.Nombre)
	return i, err
}

const createLiga = `-- name: CreateLiga :one

INSERT INTO ligas (nombre, pais) 
VALUES ($1, $2) 
RETURNING id, nombre, pais
`

type CreateLigaParams struct {
	Nombre string
	Pais   string
}

// CRUD PARA LA TABLA PRINCIPAL: LIGAS
func (q *Queries) CreateLiga(ctx context.Context, arg CreateLigaParams) (Liga, error) {
	row := q.db.QueryRowContext(ctx, createLiga, arg.Nombre, arg.Pais)
	var i Liga
	err := row.Scan(&i.ID, &i.Nombre, &i.Pais)
	return i, err
}

const createPartido = `-- name: CreatePartido :one

INSERT INTO partidos (liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado)
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado
`

type CreatePartidoParams struct {
	LigaID            int32
	EquipoLocalID     int32
	EquipoVisitanteID int32
	GolesLocal        sql.NullInt32
	GolesVisitante    sql.NullInt32
	Estado            sql.NullString
}

// CRUD PARA LA TABLA PRINCIPAL: PARTIDOS
func (q *Queries) CreatePartido(ctx context.Context, arg CreatePartidoParams) (Partido, error) {
	row := q.db.QueryRowContext(ctx, createPartido,
		arg.LigaID,
		arg.EquipoLocalID,
		arg.EquipoVisitanteID,
		arg.GolesLocal,
		arg.GolesVisitante,
		arg.Estado,
	)
	var i Partido
	err := row.Scan(
		&i.ID,
		&i.LigaID,
		&i.EquipoLocalID,
		&i.EquipoVisitanteID,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Estado,
	)
	return i, err
}

const createTabla = `-- name: CreateTabla :one

INSERT INTO tabla_posiciones (liga_id, equipo_id)
VALUES ($1, $2) 
RETURNING id, liga_id, equipo_id, puntos, partidos_jugados, partidos_ganados, partidos_empatados, partidos_perdidos
`

type CreateTablaParams struct {
	LigaID   int32
	EquipoID int32
}

// CRUD PARA LA TABLA PRINCIPAL: TABLA DE POSICIONES
func (q *Queries) CreateTabla(ctx context.Context, arg CreateTablaParams) (TablaPosicione, error) {
	row := q.db.QueryRowContext(ctx, createTabla, arg.LigaID, arg.EquipoID)
	var i TablaPosicione
	err := row.Scan(
		&i.ID,
		&i.LigaID,
		&i.EquipoID,
		&i.Puntos,
		&i.PartidosJugados,
		&i.PartidosGanados,
		&i.PartidosEmpatados,
		&i.PartidosPerdidos,
	)
	return i, err
}

const deleteEquipo = `-- name: DeleteEquipo :exec

DELETE FROM equipos 
WHERE id = $1
`

// Devuelve el id asiginado del equipo actualizado
func (q *Queries) DeleteEquipo(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEquipo, id)
	return err
}

const deleteEquipoDeTabla = `-- name: DeleteEquipoDeTabla :exec
DELETE FROM tabla_posiciones
WHERE liga_id = $1 AND equipo_id = $2
`

type DeleteEquipoDeTablaParams struct {
	LigaID   int32
	EquipoID int32
}

// elimina un equipo de la tabla de posiciones de una liga en especifico
func (q *Queries) DeleteEquipoDeTabla(ctx context.Context, arg DeleteEquipoDeTablaParams) error {
	_, err := q.db.ExecContext(ctx, deleteEquipoDeTabla, arg.LigaID, arg.EquipoID)
	return err
}

const deleteLiga = `-- name: DeleteLiga :exec
DELETE FROM ligas
WHERE id = $1
`

func (q *Queries) DeleteLiga(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLiga, id)
	return err
}

const deletePartido = `-- name: DeletePartido :exec
DELETE FROM partidos
WHERE id = $1
`

func (q *Queries) DeletePartido(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePartido, id)
	return err
}

const getEquipo = `-- name: GetEquipo :one

SELECT id, nombre FROM equipos 
WHERE id = $1
`

// Devuelve el id asiginado del nuevo equipo creado
func (q *Queries) GetEquipo(ctx context.Context, id int32) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, getEquipo, id)
	var i Equipo
	err := row.Scan(&i.ID, &i.Nombre)
	return i, err
}

const getLiga = `-- name: GetLiga :one

SELECT id, nombre, pais FROM ligas
WHERE id = $1
`

// Devuelve el id asiginado de la nueva liga creada
func (q *Queries) GetLiga(ctx context.Context, id int32) (Liga, error) {
	row := q.db.QueryRowContext(ctx, getLiga, id)
	var i Liga
	err := row.Scan(&i.ID, &i.Nombre, &i.Pais)
	return i, err
}

const getPartido = `-- name: GetPartido :one

SELECT id, liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado FROM partidos 
WHERE id = $1
`

// Devuelve el id asiginado del nuevo partido creado
func (q *Queries) GetPartido(ctx context.Context, id int32) (Partido, error) {
	row := q.db.QueryRowContext(ctx, getPartido, id)
	var i Partido
	err := row.Scan(
		&i.ID,
		&i.LigaID,
		&i.EquipoLocalID,
		&i.EquipoVisitanteID,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Estado,
	)
	return i, err
}

const listEquipos = `-- name: ListEquipos :many
SELECT id, nombre FROM equipos 
ORDER BY nombre ASC
`

func (q *Queries) ListEquipos(ctx context.Context) ([]Equipo, error) {
	rows, err := q.db.QueryContext(ctx, listEquipos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipo
	for rows.Next() {
		var i Equipo
		if err := rows.Scan(&i.ID, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLigas = `-- name: ListLigas :many
SELECT id, nombre, pais FROM ligas
ORDER BY nombre ASC
`

func (q *Queries) ListLigas(ctx context.Context) ([]Liga, error) {
	rows, err := q.db.QueryContext(ctx, listLigas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Liga
	for rows.Next() {
		var i Liga
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Pais); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartidos = `-- name: ListPartidos :many
SELECT id, liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado FROM partidos 
ORDER BY id DESC
`

// lista todos los partidos del dia sin importar la liga a la que pertezcan
func (q *Queries) ListPartidos(ctx context.Context) ([]Partido, error) {
	rows, err := q.db.QueryContext(ctx, listPartidos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partido
	for rows.Next() {
		var i Partido
		if err := rows.Scan(
			&i.ID,
			&i.LigaID,
			&i.EquipoLocalID,
			&i.EquipoVisitanteID,
			&i.GolesLocal,
			&i.GolesVisitante,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartidosLiga = `-- name: ListPartidosLiga :many
SELECT id, liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado FROM partidos 
WHERE liga_id = $1
`

// lista los partidos de una liga en especifico, sin importar el estado del partido
func (q *Queries) ListPartidosLiga(ctx context.Context, ligaID int32) ([]Partido, error) {
	rows, err := q.db.QueryContext(ctx, listPartidosLiga, ligaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partido
	for rows.Next() {
		var i Partido
		if err := rows.Scan(
			&i.ID,
			&i.LigaID,
			&i.EquipoLocalID,
			&i.EquipoVisitanteID,
			&i.GolesLocal,
			&i.GolesVisitante,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTabla = `-- name: ListTabla :many
SELECT e.nombre as equipo, t.puntos, t.partidos_jugados, t.partidos_ganados, t.partidos_empatados, t.partidos_perdidos
FROM tabla_posiciones t
JOIN equipos e ON t.equipo_id = e.id
WHERE t.liga_id = $1
ORDER BY t.puntos DESC, e.nombre ASC
`

type ListTablaRow struct {
	Equipo            string
	Puntos            sql.NullInt32
	PartidosJugados   sql.NullInt32
	PartidosGanados   sql.NullInt32
	PartidosEmpatados sql.NullInt32
	PartidosPerdidos  sql.NullInt32
}

func (q *Queries) ListTabla(ctx context.Context, ligaID int32) ([]ListTablaRow, error) {
	rows, err := q.db.QueryContext(ctx, listTabla, ligaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTablaRow
	for rows.Next() {
		var i ListTablaRow
		if err := rows.Scan(
			&i.Equipo,
			&i.Puntos,
			&i.PartidosJugados,
			&i.PartidosGanados,
			&i.PartidosEmpatados,
			&i.PartidosPerdidos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipo = `-- name: UpdateEquipo :exec
UPDATE equipos 
SET nombre = $2 
WHERE id = $1
RETURNING id, nombre
`

type UpdateEquipoParams struct {
	ID     int32
	Nombre string
}

func (q *Queries) UpdateEquipo(ctx context.Context, arg UpdateEquipoParams) error {
	_, err := q.db.ExecContext(ctx, updateEquipo, arg.ID, arg.Nombre)
	return err
}

const updateLiga = `-- name: UpdateLiga :exec
UPDATE  ligas
SET nombre = $2,
    pais = $3
WHERE id = $1
`

type UpdateLigaParams struct {
	ID     int32
	Nombre string
	Pais   string
}

func (q *Queries) UpdateLiga(ctx context.Context, arg UpdateLigaParams) error {
	_, err := q.db.ExecContext(ctx, updateLiga, arg.ID, arg.Nombre, arg.Pais)
	return err
}

const updatePartido = `-- name: UpdatePartido :exec
UPDATE partidos 
SET goles_local = $2, 
    goles_visitante = $3, 
    estado = $4 
WHERE id = $1
`

type UpdatePartidoParams struct {
	ID             int32
	GolesLocal     sql.NullInt32
	GolesVisitante sql.NullInt32
	Estado         sql.NullString
}

func (q *Queries) UpdatePartido(ctx context.Context, arg UpdatePartidoParams) error {
	_, err := q.db.ExecContext(ctx, updatePartido,
		arg.ID,
		arg.GolesLocal,
		arg.GolesVisitante,
		arg.Estado,
	)
	return err
}

const updateTabla = `-- name: UpdateTabla :exec

UPDATE tabla_posiciones 
SET puntos = puntos + $3, 
    partidos_jugados = partidos_jugados + 1,
    partidos_ganados = partidos_ganados + $4,
    partidos_empatados = partidos_empatados + $5,
    partidos_perdidos = partidos_perdidos + $6
WHERE liga_id = $1 AND equipo_id = $2
`

type UpdateTablaParams struct {
	LigaID            int32
	EquipoID          int32
	Puntos            sql.NullInt32
	PartidosGanados   sql.NullInt32
	PartidosEmpatados sql.NullInt32
	PartidosPerdidos  sql.NullInt32
}

// Devuelve el id de la fila creada en la tabla de posiciones (todos los ids de cada componente y las estadisticas iniciales en 0)
func (q *Queries) UpdateTabla(ctx context.Context, arg UpdateTablaParams) error {
	_, err := q.db.ExecContext(ctx, updateTabla,
		arg.LigaID,
		arg.EquipoID,
		arg.Puntos,
		arg.PartidosGanados,
		arg.PartidosEmpatados,
		arg.PartidosPerdidos,
	)
	return err
}
