// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package DataBase

import (
	"context"
	"database/sql"
)

const actualizarEstadisticas = `-- name: ActualizarEstadisticas :exec
UPDATE tabla_posiciones 
SET puntos = puntos + $3, 
    partidos_jugados = partidos_jugados + 1,
    partidos_ganados = partidos_ganados + $4,
    partidos_empatados = partidos_empatados + $5,
    partidos_perdidos = partidos_perdidos + $6
WHERE liga_id = $1 AND equipo_id = $2
`

type ActualizarEstadisticasParams struct {
	LigaID            int32
	EquipoID          int32
	Puntos            sql.NullInt32
	PartidosGanados   sql.NullInt32
	PartidosEmpatados sql.NullInt32
	PartidosPerdidos  sql.NullInt32
}

// Para sumar puntos y partidos cuando termina un encuentro
func (q *Queries) ActualizarEstadisticas(ctx context.Context, arg ActualizarEstadisticasParams) error {
	_, err := q.db.ExecContext(ctx, actualizarEstadisticas,
		arg.LigaID,
		arg.EquipoID,
		arg.Puntos,
		arg.PartidosGanados,
		arg.PartidosEmpatados,
		arg.PartidosPerdidos,
	)
	return err
}

const actualizarResultadoPartido = `-- name: ActualizarResultadoPartido :exec
UPDATE partidos 
SET goles_local = $2, goles_visitante = $3, estado = 'Finalizado'
WHERE id = $1
`

type ActualizarResultadoPartidoParams struct {
	ID             int32
	GolesLocal     sql.NullInt32
	GolesVisitante sql.NullInt32
}

// Atajo: Solo pasas los goles y automáticamente lo marca como 'Finalizado'
func (q *Queries) ActualizarResultadoPartido(ctx context.Context, arg ActualizarResultadoPartidoParams) error {
	_, err := q.db.ExecContext(ctx, actualizarResultadoPartido, arg.ID, arg.GolesLocal, arg.GolesVisitante)
	return err
}

const createEquipo = `-- name: CreateEquipo :one

INSERT INTO equipos (nombre) 
VALUES ($1) 
RETURNING id, nombre
`

// CRUD PARA LA TABLA: EQUIPOS
// Crea un nuevo registro
func (q *Queries) CreateEquipo(ctx context.Context, nombre string) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, createEquipo, nombre)
	var i Equipo
	err := row.Scan(&i.ID, &i.Nombre)
	return i, err
}

const createLiga = `-- name: CreateLiga :one

INSERT INTO ligas (nombre, pais) 
VALUES ($1, $2) RETURNING id, nombre, pais
`

type CreateLigaParams struct {
	Nombre string
	Pais   string
}

// FUNCIONES ESPECIFICAS DE LA APP
func (q *Queries) CreateLiga(ctx context.Context, arg CreateLigaParams) (Liga, error) {
	row := q.db.QueryRowContext(ctx, createLiga, arg.Nombre, arg.Pais)
	var i Liga
	err := row.Scan(&i.ID, &i.Nombre, &i.Pais)
	return i, err
}

const createPartido = `-- name: CreatePartido :one

INSERT INTO partidos (liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado)
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado
`

type CreatePartidoParams struct {
	LigaID            int32
	EquipoLocalID     int32
	EquipoVisitanteID int32
	GolesLocal        sql.NullInt32
	GolesVisitante    sql.NullInt32
	Estado            sql.NullString
}

// CRUD PARA LA TABLA PRINCIPAL: PARTIDOS
// Crea un partido pasándole todos los datos (goles y estado)
func (q *Queries) CreatePartido(ctx context.Context, arg CreatePartidoParams) (Partido, error) {
	row := q.db.QueryRowContext(ctx, createPartido,
		arg.LigaID,
		arg.EquipoLocalID,
		arg.EquipoVisitanteID,
		arg.GolesLocal,
		arg.GolesVisitante,
		arg.Estado,
	)
	var i Partido
	err := row.Scan(
		&i.ID,
		&i.LigaID,
		&i.EquipoLocalID,
		&i.EquipoVisitanteID,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Estado,
	)
	return i, err
}

const createPartidoProgramado = `-- name: CreatePartidoProgramado :one
INSERT INTO partidos (liga_id, equipo_local_id, equipo_visitante_id)
VALUES ($1, $2, $3) RETURNING id, liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado
`

type CreatePartidoProgramadoParams struct {
	LigaID            int32
	EquipoLocalID     int32
	EquipoVisitanteID int32
}

// Alternativa rápida: Crea un partido que aún no se jugó (solo pide liga y equipos)
func (q *Queries) CreatePartidoProgramado(ctx context.Context, arg CreatePartidoProgramadoParams) (Partido, error) {
	row := q.db.QueryRowContext(ctx, createPartidoProgramado, arg.LigaID, arg.EquipoLocalID, arg.EquipoVisitanteID)
	var i Partido
	err := row.Scan(
		&i.ID,
		&i.LigaID,
		&i.EquipoLocalID,
		&i.EquipoVisitanteID,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Estado,
	)
	return i, err
}

const deleteEquipo = `-- name: DeleteEquipo :exec
DELETE FROM equipos 
WHERE id = $1
`

// Borra un registro por su ID
func (q *Queries) DeleteEquipo(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEquipo, id)
	return err
}

const deletePartido = `-- name: DeletePartido :exec
DELETE FROM partidos
WHERE id = $1
`

func (q *Queries) DeletePartido(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePartido, id)
	return err
}

const getEquipo = `-- name: GetEquipo :one
SELECT id, nombre FROM equipos 
WHERE id = $1
`

// Obtiene un registro especifico por su ID
func (q *Queries) GetEquipo(ctx context.Context, id int32) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, getEquipo, id)
	var i Equipo
	err := row.Scan(&i.ID, &i.Nombre)
	return i, err
}

const getPartido = `-- name: GetPartido :one
SELECT id, liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado FROM partidos 
WHERE id = $1
`

func (q *Queries) GetPartido(ctx context.Context, id int32) (Partido, error) {
	row := q.db.QueryRowContext(ctx, getPartido, id)
	var i Partido
	err := row.Scan(
		&i.ID,
		&i.LigaID,
		&i.EquipoLocalID,
		&i.EquipoVisitanteID,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Estado,
	)
	return i, err
}

const inicializarEquipoEnTabla = `-- name: InicializarEquipoEnTabla :one
INSERT INTO tabla_posiciones (liga_id, equipo_id)
VALUES ($1, $2) RETURNING id, liga_id, equipo_id, puntos, partidos_jugados, partidos_ganados, partidos_empatados, partidos_perdidos
`

type InicializarEquipoEnTablaParams struct {
	LigaID   int32
	EquipoID int32
}

// Agrega un equipo a la tabla de una liga con 0 puntos
func (q *Queries) InicializarEquipoEnTabla(ctx context.Context, arg InicializarEquipoEnTablaParams) (TablaPosicione, error) {
	row := q.db.QueryRowContext(ctx, inicializarEquipoEnTabla, arg.LigaID, arg.EquipoID)
	var i TablaPosicione
	err := row.Scan(
		&i.ID,
		&i.LigaID,
		&i.EquipoID,
		&i.Puntos,
		&i.PartidosJugados,
		&i.PartidosGanados,
		&i.PartidosEmpatados,
		&i.PartidosPerdidos,
	)
	return i, err
}

const listEquipos = `-- name: ListEquipos :many
SELECT id, nombre FROM equipos 
ORDER BY nombre ASC
`

// Lista todos los registros
func (q *Queries) ListEquipos(ctx context.Context) ([]Equipo, error) {
	rows, err := q.db.QueryContext(ctx, listEquipos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipo
	for rows.Next() {
		var i Equipo
		if err := rows.Scan(&i.ID, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartidos = `-- name: ListPartidos :many
SELECT id, liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado FROM partidos 
ORDER BY id DESC
`

func (q *Queries) ListPartidos(ctx context.Context) ([]Partido, error) {
	rows, err := q.db.QueryContext(ctx, listPartidos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partido
	for rows.Next() {
		var i Partido
		if err := rows.Scan(
			&i.ID,
			&i.LigaID,
			&i.EquipoLocalID,
			&i.EquipoVisitanteID,
			&i.GolesLocal,
			&i.GolesVisitante,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPartidosPorLiga = `-- name: ListarPartidosPorLiga :many
SELECT id, liga_id, equipo_local_id, equipo_visitante_id, goles_local, goles_visitante, estado FROM partidos 
WHERE liga_id = $1
`

// Para mostrar todos los partidos de una liga específica
func (q *Queries) ListarPartidosPorLiga(ctx context.Context, ligaID int32) ([]Partido, error) {
	rows, err := q.db.QueryContext(ctx, listarPartidosPorLiga, ligaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partido
	for rows.Next() {
		var i Partido
		if err := rows.Scan(
			&i.ID,
			&i.LigaID,
			&i.EquipoLocalID,
			&i.EquipoVisitanteID,
			&i.GolesLocal,
			&i.GolesVisitante,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerTablaDePosiciones = `-- name: ObtenerTablaDePosiciones :many
SELECT e.nombre as equipo, t.puntos, t.partidos_jugados, t.partidos_ganados, t.partidos_empatados, t.partidos_perdidos
FROM tabla_posiciones t
JOIN equipos e ON t.equipo_id = e.id
WHERE t.liga_id = $1
ORDER BY t.puntos DESC
`

type ObtenerTablaDePosicionesRow struct {
	Equipo            string
	Puntos            sql.NullInt32
	PartidosJugados   sql.NullInt32
	PartidosGanados   sql.NullInt32
	PartidosEmpatados sql.NullInt32
	PartidosPerdidos  sql.NullInt32
}

// ¡El corazón de Promiedos! Trae la tabla ordenada por puntos de mayor a menor.
func (q *Queries) ObtenerTablaDePosiciones(ctx context.Context, ligaID int32) ([]ObtenerTablaDePosicionesRow, error) {
	rows, err := q.db.QueryContext(ctx, obtenerTablaDePosiciones, ligaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObtenerTablaDePosicionesRow
	for rows.Next() {
		var i ObtenerTablaDePosicionesRow
		if err := rows.Scan(
			&i.Equipo,
			&i.Puntos,
			&i.PartidosJugados,
			&i.PartidosGanados,
			&i.PartidosEmpatados,
			&i.PartidosPerdidos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipo = `-- name: UpdateEquipo :exec
UPDATE equipos 
SET nombre = $2 
WHERE id = $1
`

type UpdateEquipoParams struct {
	ID     int32
	Nombre string
}

// Actualiza un registro existente
func (q *Queries) UpdateEquipo(ctx context.Context, arg UpdateEquipoParams) error {
	_, err := q.db.ExecContext(ctx, updateEquipo, arg.ID, arg.Nombre)
	return err
}

const updatePartido = `-- name: UpdatePartido :exec
UPDATE partidos 
SET goles_local = $2, 
    goles_visitante = $3, 
    estado = $4 
WHERE id = $1
`

type UpdatePartidoParams struct {
	ID             int32
	GolesLocal     sql.NullInt32
	GolesVisitante sql.NullInt32
	Estado         sql.NullString
}

// Ideal para cargar el resultado y cambiar el estado manualmente
func (q *Queries) UpdatePartido(ctx context.Context, arg UpdatePartidoParams) error {
	_, err := q.db.ExecContext(ctx, updatePartido,
		arg.ID,
		arg.GolesLocal,
		arg.GolesVisitante,
		arg.Estado,
	)
	return err
}
